

FRAME_HEIGHT = 8
FRAME_WIDTH = FRAME_HEIGHT * 16 / 9

TOP_BAR_HEIGHT = 0.5
BOTTOM_BAR_HEIGHT = 0.5
LEFT_BAR_WIDTH = 0.0
RIGHT_BAR_WIDTH = 0.0

CONTENT_HEIGHT = FRAME_HEIGHT - TOP_BAR_HEIGHT - BOTTOM_BAR_HEIGHT
CONTENT_WIDTH = FRAME_WIDTH - LEFT_BAR_WIDTH - RIGHT_BAR_WIDTH
